server:
  port: 9999
spring:
  main:
    banner-mode: 'off'
  datasource:
    url: jdbc:mysql://localhost:3306/jpa?useSSL=false&useUnicode=true&characterEncoding=UTF-8
#    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: fish119
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 初始化大小，最小，最大
      initial-size: 2
      min-idle: 2
      max-active: 5
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
  profiles:
    active: production
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
logging:
  level:
    root: WARN
    org.springframework.web: WARN
    org.hibernate: WARN
    site.fish.jpa: INFO
